CREATE TABLE IF NOT EXISTS authors (
	authorid SERIAL PRIMARY KEY,
	authorname VARCHAR(512) NOT NULL,
	email VARCHAR(512) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS maps (
	mapid SERIAL PRIMARY KEY,
	mapname VARCHAR(512) NOT NULL,
	mapdescription VARCHAR(512) NOT NULL,
	initlatitude FLOAT NOT NULL,
	initlongitude FLOAT NOT NULL,
	initzoom INTEGER NOT NULL,
	authorid INTEGER REFERENCES authors(authorid) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL
);

CREATE TABLE IF NOT EXISTS tabs (
	tabid SERIAL PRIMARY KEY,
	tabname VARCHAR(512) NOT NULL,
	mapid INTEGER REFERENCES maps(mapid) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL
);

CREATE TABLE IF NOT EXISTS pins (
	pinid SERIAL PRIMARY KEY,
	pinname VARCHAR(512) NOT NULL,
	pindescription VARCHAR(512) NOT NULL,
	imageurl VARCHAR(1024),
	category VARCHAR(64) NOT NULL,
	latitude FLOAT NOT NULL,
	longitude FLOAT NOT NULL,
	tabid INTEGER REFERENCES tabs(tabid) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL
);